apiVersion: bffx.io/v1alpha1
kind: Blueprint
metadata:
  name: OnboardingSurveyDefault
spec:
  resource: OnboardingSurvey
  fields:
    user_id: "curabitur"
    question: "curabitur"
    answer: "dolor"
