package proto

import (
	"fmt"
	"strings"

	"github.com/hangry-coder/bffx/pkg/manifest"
)

// BuildProto generates a pure-Go string representing a unified .proto schema
// for all active resources, actions, builders, and pipelines in the registry.
func BuildProto(reg *manifest.Registry, wirePackage string) string {
	if wirePackage == "" {
		wirePackage = "bffx.v1"
	}

	var sb strings.Builder

	// 1. Gather all fields to determine dynamic imports
	hasStruct := false
	hasTimestamp := false

	// Scan resources
	for _, r := range reg.Resources {
		var spec manifest.ResourceSpec
		_ = r.UnmarshalSpec(&spec)
		for _, f := range spec.Fields {
			if f.Type == "json" || f.Type == "map" {
				hasStruct = true
			}
			if f.Type == "date" || f.Type == "datetime" {
				hasTimestamp = true
			}
		}
	}

	// Actions, builders, pipelines, and screens use Struct for loose payloads
	if len(reg.Actions) > 0 || len(reg.Builders) > 0 || len(reg.Pipelines) > 0 || len(reg.Screens) > 0 {
		hasStruct = true
	}

	// 2. Write headers
	sb.WriteString("// Code generated by bffx sync. DO NOT EDIT.\n")
	sb.WriteString("syntax = \"proto3\";\n\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", wirePackage))

	// Write package go options
	sb.WriteString("option go_package = \"github.com/hangry-coder/bffx/.bffx/gen/go;bffxv1\";\n\n")

	// Write dynamic imports
	if hasStruct {
		sb.WriteString("import \"google/protobuf/struct.proto\";\n")
	}
	if hasTimestamp {
		sb.WriteString("import \"google/protobuf/timestamp.proto\";\n")
	}
	if hasStruct || hasTimestamp {
		sb.WriteString("\n")
	}

	// 3. Write services
	writeResourceServices(&sb, reg)
	writeActionServices(&sb, reg)
	writeBuilderServices(&sb, reg)
	writePipelineServices(&sb, reg)
	writeScreenServices(&sb, reg)

	// 4. Write messages
	writeResourceMessages(&sb, reg)
	writeActionMessages(&sb, reg)
	writeBuilderMessages(&sb, reg)
	writePipelineMessages(&sb, reg)
	writeScreenMessages(&sb, reg)

	return sb.String()
}

func mapFieldType(t string) string {
	switch t {
	case "string", "text", "email", "uuid":
		return "string"
	case "int":
		return "int64"
	case "float":
		return "double"
	case "bool":
		return "bool"
	case "file":
		return "string"
	case "json", "map":
		return "google.protobuf.Struct"
	case "date", "datetime":
		return "google.protobuf.Timestamp"
	default:
		return "string"
	}
}

func writeResourceServices(sb *strings.Builder, reg *manifest.Registry) {
	for _, r := range reg.Resources {
		var spec manifest.ResourceSpec
		_ = r.UnmarshalSpec(&spec)

		// Check transport gating
		if len(spec.Transports) > 0 {
			grpcAllowed := false
			for _, t := range spec.Transports {
				if strings.ToLower(t) == "grpc" {
					grpcAllowed = true
					break
				}
			}
			if !grpcAllowed {
				continue
			}
		}

		if spec.Routes.Crud {
			name := r.Metadata.Name
			sb.WriteString(fmt.Sprintf("service %sService {\n", name))
			sb.WriteString(fmt.Sprintf("  rpc List%ss(List%ssRequest) returns (List%ssResponse);\n", name, name, name))
			sb.WriteString(fmt.Sprintf("  rpc Get%s(Get%sRequest) returns (%s);\n", name, name, name))
			sb.WriteString(fmt.Sprintf("  rpc Create%s(Create%sRequest) returns (%s);\n", name, name, name))
			sb.WriteString(fmt.Sprintf("  rpc Update%s(Update%sRequest) returns (%s);\n", name, name, name))
			sb.WriteString(fmt.Sprintf("  rpc Delete%s(Delete%sRequest) returns (Delete%sResponse);\n", name, name, name))
			sb.WriteString("}\n\n")
		}
	}
}

func writeActionServices(sb *strings.Builder, reg *manifest.Registry) {
	activeActions := 0
	for _, a := range reg.Actions {
		var spec manifest.ActionSpec
		_ = a.UnmarshalSpec(&spec)
		if len(spec.Transports) > 0 {
			grpcAllowed := false
			for _, t := range spec.Transports {
				if strings.ToLower(t) == "grpc" {
					grpcAllowed = true
					break
				}
			}
			if !grpcAllowed {
				continue
			}
		}
		activeActions++
	}

	if activeActions > 0 {
		sb.WriteString("service ActionService {\n")
		for _, a := range reg.Actions {
			var spec manifest.ActionSpec
			_ = a.UnmarshalSpec(&spec)
			if len(spec.Transports) > 0 {
				grpcAllowed := false
				for _, t := range spec.Transports {
					if strings.ToLower(t) == "grpc" {
						grpcAllowed = true
						break
					}
				}
				if !grpcAllowed {
					continue
				}
			}
			name := a.Metadata.Name
			sb.WriteString(fmt.Sprintf("  rpc %s(%sRequest) returns (%sResponse);\n", name, name, name))
		}
		sb.WriteString("}\n\n")
	}
}

func writeBuilderServices(sb *strings.Builder, reg *manifest.Registry) {
	activeBuilders := 0
	for _, b := range reg.Builders {
		var spec manifest.BuilderSpec
		_ = b.UnmarshalSpec(&spec)
		if len(spec.Transports) > 0 {
			grpcAllowed := false
			for _, t := range spec.Transports {
				if strings.ToLower(t) == "grpc" {
					grpcAllowed = true
					break
				}
			}
			if !grpcAllowed {
				continue
			}
		}
		activeBuilders++
	}

	if activeBuilders > 0 {
		sb.WriteString("service BuilderService {\n")
		for _, b := range reg.Builders {
			var spec manifest.BuilderSpec
			_ = b.UnmarshalSpec(&spec)
			if len(spec.Transports) > 0 {
				grpcAllowed := false
				for _, t := range spec.Transports {
					if strings.ToLower(t) == "grpc" {
						grpcAllowed = true
						break
					}
				}
				if !grpcAllowed {
					continue
				}
			}
			name := b.Metadata.Name
			sb.WriteString(fmt.Sprintf("  rpc Get%s(Get%sRequest) returns (Get%sResponse);\n", name, name, name))
		}
		sb.WriteString("}\n\n")
	}
}

func writePipelineServices(sb *strings.Builder, reg *manifest.Registry) {
	activePipelines := 0
	for _, p := range reg.Pipelines {
		var spec manifest.PipelineSpec
		_ = p.UnmarshalSpec(&spec)
		if len(spec.Transports) > 0 {
			grpcAllowed := false
			for _, t := range spec.Transports {
				if strings.ToLower(t) == "grpc" {
					grpcAllowed = true
					break
				}
			}
			if !grpcAllowed {
				continue
			}
		}
		activePipelines++
	}

	if activePipelines > 0 {
		sb.WriteString("service PipelineService {\n")
		for _, p := range reg.Pipelines {
			var spec manifest.PipelineSpec
			_ = p.UnmarshalSpec(&spec)
			if len(spec.Transports) > 0 {
				grpcAllowed := false
				for _, t := range spec.Transports {
					if strings.ToLower(t) == "grpc" {
						grpcAllowed = true
						break
					}
				}
				if !grpcAllowed {
					continue
				}
			}
			name := p.Metadata.Name
			sb.WriteString(fmt.Sprintf("  rpc Process%s(Process%sRequest) returns (Process%sResponse);\n", name, name, name))
		}
		sb.WriteString("}\n\n")
	}
}

func writeResourceMessages(sb *strings.Builder, reg *manifest.Registry) {
	for _, r := range reg.Resources {
		var spec manifest.ResourceSpec
		_ = r.UnmarshalSpec(&spec)

		// Check transport gating
		if len(spec.Transports) > 0 {
			grpcAllowed := false
			for _, t := range spec.Transports {
				if strings.ToLower(t) == "grpc" {
					grpcAllowed = true
					break
				}
			}
			if !grpcAllowed {
				continue
			}
		}

		name := r.Metadata.Name
		sb.WriteString(fmt.Sprintf("message %s {\n", name))
		idx := 1
		// Core ID field
		sb.WriteString(fmt.Sprintf("  string id = %d;\n", idx))
		idx++

		for _, f := range spec.Fields {
			if f.Name == "id" {
				continue
			}
			pbType := mapFieldType(f.Type)
			sb.WriteString(fmt.Sprintf("  %s %s = %d;\n", pbType, f.Name, idx))
			idx++
		}
		sb.WriteString("}\n\n")

		if spec.Routes.Crud {
			sb.WriteString(fmt.Sprintf("message List%ssRequest {\n", name))
			sb.WriteString("  int32 limit = 1;\n")
			sb.WriteString("  int32 offset = 2;\n")
			sb.WriteString("}\n\n")

			sb.WriteString(fmt.Sprintf("message List%ssResponse {\n", name))
			sb.WriteString(fmt.Sprintf("  repeated %s items = 1;\n", name))
			sb.WriteString("  int32 total = 2;\n")
			sb.WriteString("}\n\n")

			sb.WriteString(fmt.Sprintf("message Get%sRequest {\n", name))
			sb.WriteString("  string id = 1;\n")
			sb.WriteString("}\n\n")

			sb.WriteString(fmt.Sprintf("message Create%sRequest {\n", name))
			idx = 1
			for _, f := range spec.Fields {
				if f.Name == "id" {
					continue
				}
				pbType := mapFieldType(f.Type)
				sb.WriteString(fmt.Sprintf("  %s %s = %d;\n", pbType, f.Name, idx))
				idx++
			}
			sb.WriteString("}\n\n")

			sb.WriteString(fmt.Sprintf("message Update%sRequest {\n", name))
			sb.WriteString("  string id = 1;\n")
			idx = 2
			for _, f := range spec.Fields {
				if f.Name == "id" {
					continue
				}
				pbType := mapFieldType(f.Type)
				sb.WriteString(fmt.Sprintf("  %s %s = %d;\n", pbType, f.Name, idx))
				idx++
			}
			sb.WriteString("}\n\n")

			sb.WriteString(fmt.Sprintf("message Delete%sRequest {\n", name))
			sb.WriteString("  string id = 1;\n")
			sb.WriteString("}\n\n")

			sb.WriteString(fmt.Sprintf("message Delete%sResponse {\n", name))
			sb.WriteString("  bool success = 1;\n")
			sb.WriteString("}\n\n")
		}
	}
}

func writeActionMessages(sb *strings.Builder, reg *manifest.Registry) {
	for _, a := range reg.Actions {
		var spec manifest.ActionSpec
		_ = a.UnmarshalSpec(&spec)
		if len(spec.Transports) > 0 {
			grpcAllowed := false
			for _, t := range spec.Transports {
				if strings.ToLower(t) == "grpc" {
					grpcAllowed = true
					break
				}
			}
			if !grpcAllowed {
				continue
			}
		}

		name := a.Metadata.Name
		sb.WriteString(fmt.Sprintf("message %sRequest {\n", name))
		sb.WriteString("  google.protobuf.Struct payload = 1;\n")
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("message %sResponse {\n", name))
		sb.WriteString("  google.protobuf.Struct result = 1;\n")
		sb.WriteString("}\n\n")
	}
}

func writeBuilderMessages(sb *strings.Builder, reg *manifest.Registry) {
	for _, b := range reg.Builders {
		var spec manifest.BuilderSpec
		_ = b.UnmarshalSpec(&spec)
		if len(spec.Transports) > 0 {
			grpcAllowed := false
			for _, t := range spec.Transports {
				if strings.ToLower(t) == "grpc" {
					grpcAllowed = true
					break
				}
			}
			if !grpcAllowed {
				continue
			}
		}

		name := b.Metadata.Name
		sb.WriteString(fmt.Sprintf("message Get%sRequest {\n", name))
		sb.WriteString("  google.protobuf.Struct params = 1;\n")
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("message Get%sResponse {\n", name))
		sb.WriteString("  google.protobuf.Struct result = 1;\n")
		sb.WriteString("}\n\n")
	}
}

func writePipelineMessages(sb *strings.Builder, reg *manifest.Registry) {
	for _, p := range reg.Pipelines {
		var spec manifest.PipelineSpec
		_ = p.UnmarshalSpec(&spec)
		if len(spec.Transports) > 0 {
			grpcAllowed := false
			for _, t := range spec.Transports {
				if strings.ToLower(t) == "grpc" {
					grpcAllowed = true
					break
				}
			}
			if !grpcAllowed {
				continue
			}
		}

		name := p.Metadata.Name
		sb.WriteString(fmt.Sprintf("message Process%sRequest {\n", name))
		sb.WriteString("  google.protobuf.Struct payload = 1;\n")
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("message Process%sResponse {\n", name))
		sb.WriteString("  google.protobuf.Struct result = 1;\n")
		sb.WriteString("}\n\n")
	}
}

// writeScreenServices emits one `<Screen>ScreenService` per Screen manifest.
// Each service has a single `Get(<Screen>Request) returns (<Screen>Response)`
// RPC; when `spec.stream: true`, a server-streaming `Watch(<Screen>Request)
// returns (stream <Screen>Response)` is also emitted.
//
// Strongly-typed per-Screen services mean each Screen has a distinct gRPC
// method set, which keeps mobile clients fluent (clientV1.UserProfileScreen.Get())
// and lets each screen evolve independently. See plan §5.
func writeScreenServices(sb *strings.Builder, reg *manifest.Registry) {
	for _, s := range reg.Screens {
		var spec manifest.ScreenSpec
		_ = s.UnmarshalSpec(&spec)

		if !grpcAllowedForScreen(spec.Transports) {
			continue
		}

		title := screenProtoTitle(s, &spec)
		sb.WriteString(fmt.Sprintf("service %sScreenService {\n", title))
		sb.WriteString(fmt.Sprintf("  rpc Get(%sRequest) returns (%sResponse);\n", title, title))
		if spec.Stream {
			sb.WriteString(fmt.Sprintf("  rpc Watch(%sRequest) returns (stream %sResponse);\n", title, title))
		}
		sb.WriteString("}\n\n")
	}
}

// writeScreenMessages emits a request/response message pair per Screen.
// Both use google.protobuf.Struct so changes to the source manifest don't
// require regenerating client code. Per-section payloads are surfaced via
// the response's `sections` field.
func writeScreenMessages(sb *strings.Builder, reg *manifest.Registry) {
	for _, s := range reg.Screens {
		var spec manifest.ScreenSpec
		_ = s.UnmarshalSpec(&spec)

		if !grpcAllowedForScreen(spec.Transports) {
			continue
		}

		title := screenProtoTitle(s, &spec)
		sb.WriteString(fmt.Sprintf("message %sRequest {\n", title))
		sb.WriteString("  google.protobuf.Struct params = 1;\n")
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("message %sResponse {\n", title))
		sb.WriteString("  google.protobuf.Struct output = 1;\n")
		sb.WriteString("  map<string, google.protobuf.Struct> sections = 2;\n")
		sb.WriteString("  string version_hash = 3;\n")
		sb.WriteString("  bool killed = 4;\n")
		sb.WriteString("  string kill_reason = 5;\n")
		sb.WriteString("}\n\n")
	}
}

func grpcAllowedForScreen(transports []string) bool {
	if len(transports) == 0 {
		return true
	}
	for _, t := range transports {
		if strings.ToLower(t) == "grpc" {
			return true
		}
	}
	return false
}

// screenProtoTitle returns the TitleCase identifier used to derive the
// `<Title>ScreenService`, `<Title>Request`, and `<Title>Response` symbols
// in the generated proto. Preference order:
//  1. `spec.name` from the manifest (e.g. "Home"           -> "Home"),
//  2. otherwise the auto-derived `metadata.name` minus any trailing
//     `_screen` segment (e.g. "mobile_screens_home_screen" -> "MobileScreensHome").
// Stripping the redundant `_screen` suffix prevents the doubled
// `ScreenScreenService` symbol when teams keep `_screen.yaml` filenames.
func screenProtoTitle(m *manifest.Manifest, spec *manifest.ScreenSpec) string {
	if spec != nil && strings.TrimSpace(spec.Name) != "" {
		return titleCase(spec.Name)
	}
	name := m.Metadata.Name
	if strings.HasSuffix(name, "_screen") {
		name = strings.TrimSuffix(name, "_screen")
	}
	return titleCase(name)
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
