#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

mkdir -p "${ROOT}/.bffx/bin"
GOBIN="${ROOT}/.bffx/bin" go install ./cmd/bffx
export PATH="${ROOT}/.bffx/bin:$PATH"
export GOWORK=off

REPORT_DIR="${ROOT}/.bffx"
REPORT_FILE="${REPORT_DIR}/architecture-baseline.md"
mkdir -p "$REPORT_DIR"

ms_now() {
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import time; print(int(time.time() * 1000))'
  else
    echo $(($(date +%s) * 1000))
  fi
}

size_bytes() {
  local p="$1"
  wc -c < "$p" | tr -d ' '
}

core_size_bytes() {
  local core_dir="$1/.bffx/core"
  if [[ ! -d "$core_dir" ]]; then
    echo "0"
    return
  fi
  du -sk "$core_dir" | awk '{print $1 * 1024}'
}

resolve_cmd_path() {
  local path="$1"
  if [[ -d "$ROOT/$path/cmd/api" ]]; then
    echo "./cmd/api"
  else
    echo "./cmd/orchestrator"
  fi
}

benchmark_project() {
  local name="$1"
  local path="$2"
  local cmd_path="${3:-$(resolve_cmd_path "$path")}"

  echo "Benchmarking ${name} (${path})..."
  pushd "$ROOT/$path" >/dev/null

  local s1 e1 s2 e2 sync_ms build_ms bin_size core_bytes
  s1="$(ms_now)"
  bffx sync
  e1="$(ms_now)"
  sync_ms="$((e1 - s1))"

  core_bytes="$(core_size_bytes ".")"

  s2="$(ms_now)"
  go build -o .bffx/orchestrator.baseline "$cmd_path"
  e2="$(ms_now)"
  build_ms="$((e2 - s2))"
  bin_size="$(size_bytes ".bffx/orchestrator.baseline")"

  cat <<EOF >> "$REPORT_FILE"
| ${name} | ${path} | ${sync_ms} | ${build_ms} | ${bin_size} | ${core_bytes} |
EOF

  popd >/dev/null
}

cat <<'EOF' > "$REPORT_FILE"
# Architecture Baseline Report

Generated by `scripts/ci/architecture-baseline.sh`.

| Fixture | Path | Sync ms | Build ms | Binary bytes | `.bffx/core` bytes |
|---|---|---:|---:|---:|---:|
EOF

benchmark_project "Notes" "examples/notes"
benchmark_project "PipelinesCalorie" "examples/pipelines-calorie"

echo
echo "Wrote baseline report: ${REPORT_FILE}"
cat "$REPORT_FILE"
