apiVersion: bffx.io/v1alpha1
kind: Resource
metadata:
  name: OnboardingSurvey
spec:
  group: mobile
  fields:
    - { name: user_id, type: string }
    - { name: question, type: string }
    - { name: answer, type: string }
  routes:
    crud: true
  policy:
    read: owner
    write: owner
  hooks: {}
