apiVersion: bffx.io/v1alpha1
kind: Screen
metadata:
  name: IntroCarousel
spec:
  group: mobile
  name: IntroCarousel
  nav_type: onboarding
  icon: 
  order: 0
  requires_auth: 
  route:
    method: GET
    path: /api/v1/screens/introcarousel
    auth: optional
  sources: []
  output: {}
