apiVersion: bffx.io/v1alpha1
kind: Screen
metadata:
  name: Signup
spec:
  group: mobile
  name: Signup
  nav_type: auth_flow
  icon: 
  order: 0
  requires_auth: 
  route:
    method: GET
    path: /api/v1/screens/signup
    auth: optional
  sources: []
  output: {}
