package main

import (
	"github.com/hangry-coder/bffx/pkg/api/handlers"
	"github.com/hangry-coder/bffx/pkg/api/router"
	meetingshooks "dictation/internal/features/meetings/hooks"
	mobilehooks "dictation/internal/features/mobile/hooks"
	systemhooks "dictation/internal/features/system/hooks"
)

// Code generated by bffx sync. DO NOT EDIT.
var ActionHandlers = map[string]handlers.ActionHandler{
	"CompleteProfile": mobilehooks.HandleCompleteProfile,
	"MockTranscribe": meetingshooks.HandleMockTranscribe,
	"VerifyOTP": systemhooks.HandleVerifyOTP,
}

var HookHandlers = map[string]router.HookFunc{
	"AfterAudioUpload": meetingshooks.AfterAudioUpload,
	"BeforeAudioUpload": meetingshooks.BeforeAudioUpload,
	"CheckVerification": systemhooks.CheckVerification,
	"SendOTP": systemhooks.SendOTP,
	"SendWelcome": systemhooks.SendWelcome,
}
