package main

import (
	"github.com/hangry-coder/bffx/pkg/api/handlers"
	"github.com/hangry-coder/bffx/pkg/api/router"
	financehooks "fintech/internal/features/finance/hooks"
	mobilehooks "fintech/internal/features/mobile/hooks"
	systemhooks "fintech/internal/features/system/hooks"
)

// Code generated by bffx sync. DO NOT EDIT.
var ActionHandlers = map[string]handlers.ActionHandler{
	"CompleteProfile": mobilehooks.HandleCompleteProfile,
	"PlaidWebhook": financehooks.HandlePlaidWebhook,
	"VerifyOTP": systemhooks.HandleVerifyOTP,
}

var HookHandlers = map[string]router.HookFunc{
	"AfterReceiptScan": financehooks.AfterReceiptScan,
	"BeforeReceiptScan": financehooks.BeforeReceiptScan,
	"CheckVerification": systemhooks.CheckVerification,
	"SendOTP": systemhooks.SendOTP,
	"SendWelcome": systemhooks.SendWelcome,
}
