package generator

// typedConvertersSource is emitted once into .bffx/gen/types/ alongside per-resource structs.
const typedConvertersSource = `// Code generated by bffx sync. DO NOT EDIT.
package types

import (
	"encoding/json"
	"fmt"
	"github.com/hangry-coder/bffx/pkg/i18n"
)

func stringFromAny(v any) string {
	if v == nil {
		return ""
	}
	switch t := v.(type) {
	case string:
		return t
	default:
		return fmt.Sprintf("%v", v)
	}
}

func boolFromAny(v any) bool {
	if v == nil {
		return false
	}
	switch t := v.(type) {
	case bool:
		return t
	case string:
		return t == "true" || t == "1"
	case float64:
		return t != 0
	case int:
		return t != 0
	default:
		return false
	}
}

func intFromAny(v any) int {
	if v == nil {
		return 0
	}
	switch t := v.(type) {
	case int:
		return t
	case int32:
		return int(t)
	case int64:
		return int(t)
	case float64:
		return int(t)
	case float32:
		return int(t)
	default:
		return 0
	}
}

func floatFromAny(v any) float64 {
	if v == nil {
		return 0
	}
	switch t := v.(type) {
	case float64:
		return t
	case float32:
		return float64(t)
	case int:
		return float64(t)
	case int64:
		return float64(t)
	default:
		return 0
	}
}

func localizedStringFromAny(v any) i18n.LocalizedString {
	if v == nil {
		return nil
	}
	switch t := v.(type) {
	case i18n.LocalizedString:
		return t
	case map[string]string:
		return i18n.LocalizedString(t)
	case map[string]any:
		res := make(i18n.LocalizedString)
		for k, val := range t {
			if s, ok := val.(string); ok {
				res[k] = s
			} else {
				res[k] = fmt.Sprintf("%v", val)
			}
		}
		return res
	case string:
		var res i18n.LocalizedString
		if err := json.Unmarshal([]byte(t), &res); err == nil {
			return res
		}
		return i18n.LocalizedString{"en": t}
	default:
		return nil
	}
}
`
