package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/hangry-coder/bffx/pkg/manifest"
)

var safeIdent = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]*$`)

// EmitTypedModels writes one Go file per resource under .bffx/gen/types/ (package types).
// This is a pilot for typed hook boundaries (Week 8); structs include ToMap/FromMap helpers.
func EmitTypedModels(root string, reg *manifest.Registry) error {
	outDir := filepath.Join(root, ".bffx", "gen", "types")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir typed models: %w", err)
	}

	helperPath := filepath.Join(outDir, "bffx_types_helpers.gen.go")
	if err := os.WriteFile(helperPath, []byte(typedConvertersSource), 0o644); err != nil {
		return fmt.Errorf("write typed helpers: %w", err)
	}

	for _, res := range reg.Resources {
		name := res.Metadata.Name
		if !safeIdent.MatchString(name) {
			continue
		}
		var spec manifest.ResourceSpec
		if err := res.UnmarshalSpec(&spec); err != nil {
			continue
		}
		code, err := renderTypedResource(name, &spec)
		if err != nil {
			return err
		}
		fname := strings.ToLower(name) + "_types.gen.go"
		path := filepath.Join(outDir, fname)
		if err := os.WriteFile(path, []byte(code), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", fname, err)
		}
	}
	return nil
}

func renderTypedResource(goName string, spec *manifest.ResourceSpec) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by bffx sync. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package types\n\n")
	
	hasLocalized := false
	for _, f := range spec.Fields {
		if strings.ToLower(f.Type) == "localized_string" {
			hasLocalized = true
			break
		}
	}
	if hasLocalized {
		fmt.Fprintf(&b, "import \"github.com/hangry-coder/bffx/pkg/i18n\"\n\n")
	}

	fmt.Fprintf(&b, "// %s is a typed view of manifest resource %q.\n", goName, goName)
	fmt.Fprintf(&b, "type %s struct {\n", goName)
	hasID := false
	for _, f := range spec.Fields {
		if f.Name == "id" {
			hasID = true
			break
		}
	}
	if !hasID {
		fmt.Fprintf(&b, "\tID string `json:\"id\"`\n")
	}
	for _, f := range spec.Fields {
		if !safeIdent.MatchString(f.Name) {
			continue
		}
		goField := toExportedFieldName(f.Name)
		goType := manifestFieldToGoType(f.Type)
		fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", goField, goType, f.Name)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// ToMap converts the struct to the map shape used by storage and hooks.\n")
	fmt.Fprintf(&b, "func (m *%s) ToMap() map[string]any {\n", goName)
	fmt.Fprintf(&b, "\tif m == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(&b, "\treturn map[string]any{\n")
	if !hasID {
		fmt.Fprintf(&b, "\t\t\"id\": m.ID,\n")
	}
	for _, f := range spec.Fields {
		if !safeIdent.MatchString(f.Name) {
			continue
		}
		goField := toExportedFieldName(f.Name)
		fmt.Fprintf(&b, "\t\t%q: m.%s,\n", f.Name, goField)
	}
	fmt.Fprintf(&b, "\t}\n}\n\n")

	fmt.Fprintf(&b, "// FromMap fills the struct from a storage/hook payload (best-effort coercions).\n")
	fmt.Fprintf(&b, "func (m *%s) FromMap(row map[string]any) {\n", goName)
	fmt.Fprintf(&b, "\tif m == nil || row == nil {\n\t\treturn\n\t}\n")
	if !hasID {
		fmt.Fprintf(&b, "\tif v, ok := row[\"id\"]; ok {\n\t\tm.ID = stringFromAny(v)\n\t}\n")
	}
	for _, f := range spec.Fields {
		if !safeIdent.MatchString(f.Name) {
			continue
		}
		goField := toExportedFieldName(f.Name)
		writeFromMapField(&b, goName, goField, f.Name, f.Type)
	}
	fmt.Fprintf(&b, "}\n")
	return b.String(), nil
}

func toExportedFieldName(yamlName string) string {
	if yamlName == "" {
		return ""
	}
	if yamlName == "id" {
		return "ID"
	}
	return strings.ToUpper(yamlName[:1]) + yamlName[1:]
}

func manifestFieldToGoType(t string) string {
	switch strings.ToLower(strings.TrimSpace(t)) {
	case "int", "integer":
		return "int"
	case "float", "double", "number":
		return "float64"
	case "bool", "boolean":
		return "bool"
	case "localized_string":
		return "i18n.LocalizedString"
	default:
		return "string"
	}
}

func writeFromMapField(b *strings.Builder, structName, goField, jsonKey, typ string) {
	key := jsonKey
	switch strings.ToLower(strings.TrimSpace(typ)) {
	case "int", "integer":
		fmt.Fprintf(b, "\tif v, ok := row[%q]; ok {\n\t\tm.%s = intFromAny(v)\n\t}\n", key, goField)
	case "float", "double", "number":
		fmt.Fprintf(b, "\tif v, ok := row[%q]; ok {\n\t\tm.%s = floatFromAny(v)\n\t}\n", key, goField)
	case "bool", "boolean":
		fmt.Fprintf(b, "\tif v, ok := row[%q]; ok {\n\t\tm.%s = boolFromAny(v)\n\t}\n", key, goField)
	case "localized_string":
		fmt.Fprintf(b, "\tif v, ok := row[%q]; ok {\n\t\tm.%s = localizedStringFromAny(v)\n\t}\n", key, goField)
	default:
		fmt.Fprintf(b, "\tif v, ok := row[%q]; ok {\n\t\tm.%s = stringFromAny(v)\n\t}\n", key, goField)
	}
}
