apiVersion: bffx.io/v1alpha1
kind: Blueprint
metadata:
  name: AppPermissionDefault
spec:
  resource: AppPermission
  fields:
    device_id: "libero"
    location_granted: false
    notifications_granted: false
    push_granted: false
